
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserRole` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserRole
 * 
 */
export type UserRoleModel = runtime.Types.Result.DefaultSelection<Prisma.$UserRolePayload>

export type AggregateUserRole = {
  _count: UserRoleCountAggregateOutputType | null
  _min: UserRoleMinAggregateOutputType | null
  _max: UserRoleMaxAggregateOutputType | null
}

export type UserRoleMinAggregateOutputType = {
  id: string | null
  userId: string | null
  roleId: string | null
  assignedAt: Date | null
  assignedById: string | null
}

export type UserRoleMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  roleId: string | null
  assignedAt: Date | null
  assignedById: string | null
}

export type UserRoleCountAggregateOutputType = {
  id: number
  userId: number
  roleId: number
  assignedAt: number
  assignedById: number
  _all: number
}


export type UserRoleMinAggregateInputType = {
  id?: true | runtime.Types.Skip
  userId?: true | runtime.Types.Skip
  roleId?: true | runtime.Types.Skip
  assignedAt?: true | runtime.Types.Skip
  assignedById?: true | runtime.Types.Skip
}

export type UserRoleMaxAggregateInputType = {
  id?: true | runtime.Types.Skip
  userId?: true | runtime.Types.Skip
  roleId?: true | runtime.Types.Skip
  assignedAt?: true | runtime.Types.Skip
  assignedById?: true | runtime.Types.Skip
}

export type UserRoleCountAggregateInputType = {
  id?: true | runtime.Types.Skip
  userId?: true | runtime.Types.Skip
  roleId?: true | runtime.Types.Skip
  assignedAt?: true | runtime.Types.Skip
  assignedById?: true | runtime.Types.Skip
  _all?: true | runtime.Types.Skip
}

export type UserRoleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRole to aggregate.
   */
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoles to fetch.
   */
  orderBy?: Prisma.UserRoleOrderByWithRelationInput | Prisma.UserRoleOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserRoleWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoles from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoles.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserRoles
  **/
  _count?: true | UserRoleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserRoleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserRoleMaxAggregateInputType
}

export type GetUserRoleAggregateType<T extends UserRoleAggregateArgs> = {
      [P in keyof T & keyof AggregateUserRole]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserRole[P]>
    : Prisma.GetScalarType<T[P], AggregateUserRole[P]>
}




export type UserRoleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  orderBy?: Prisma.UserRoleOrderByWithAggregationInput | Prisma.UserRoleOrderByWithAggregationInput[] | runtime.Types.Skip
  by: Prisma.UserRoleScalarFieldEnum[] | Prisma.UserRoleScalarFieldEnum
  having?: Prisma.UserRoleScalarWhereWithAggregatesInput | runtime.Types.Skip
  take?: number | runtime.Types.Skip
  skip?: number | runtime.Types.Skip
  _count?: UserRoleCountAggregateInputType | true
  _min?: UserRoleMinAggregateInputType
  _max?: UserRoleMaxAggregateInputType
}

export type UserRoleGroupByOutputType = {
  id: string
  userId: string
  roleId: string
  assignedAt: Date
  assignedById: string | null
  _count: UserRoleCountAggregateOutputType | null
  _min: UserRoleMinAggregateOutputType | null
  _max: UserRoleMaxAggregateOutputType | null
}

export type GetUserRoleGroupByPayload<T extends UserRoleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserRoleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserRoleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserRoleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserRoleGroupByOutputType[P]>
      }
    >
  >



export type UserRoleWhereInput = {
  AND?: Prisma.UserRoleWhereInput | Prisma.UserRoleWhereInput[] | runtime.Types.Skip
  OR?: Prisma.UserRoleWhereInput[] | runtime.Types.Skip
  NOT?: Prisma.UserRoleWhereInput | Prisma.UserRoleWhereInput[] | runtime.Types.Skip
  id?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  userId?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  roleId?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFilter<"UserRole"> | Date | string | runtime.Types.Skip
  assignedById?: Prisma.StringNullableFilter<"UserRole"> | string | null | runtime.Types.Skip
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput> | runtime.Types.Skip
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput> | runtime.Types.Skip
  assignedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null | runtime.Types.Skip
}

export type UserRoleOrderByWithRelationInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  userId?: Prisma.SortOrder | runtime.Types.Skip
  roleId?: Prisma.SortOrder | runtime.Types.Skip
  assignedAt?: Prisma.SortOrder | runtime.Types.Skip
  assignedById?: Prisma.SortOrderInput | Prisma.SortOrder | runtime.Types.Skip
  user?: Prisma.UserOrderByWithRelationInput | runtime.Types.Skip
  role?: Prisma.RoleOrderByWithRelationInput | runtime.Types.Skip
  assignedBy?: Prisma.UserOrderByWithRelationInput | runtime.Types.Skip
}

export type UserRoleWhereUniqueInput = Prisma.AtLeast<{
  id?: string | runtime.Types.Skip
  userId_roleId?: Prisma.UserRoleUserIdRoleIdCompoundUniqueInput | runtime.Types.Skip
  AND?: Prisma.UserRoleWhereInput | Prisma.UserRoleWhereInput[] | runtime.Types.Skip
  OR?: Prisma.UserRoleWhereInput[] | runtime.Types.Skip
  NOT?: Prisma.UserRoleWhereInput | Prisma.UserRoleWhereInput[] | runtime.Types.Skip
  userId?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  roleId?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFilter<"UserRole"> | Date | string | runtime.Types.Skip
  assignedById?: Prisma.StringNullableFilter<"UserRole"> | string | null | runtime.Types.Skip
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput> | runtime.Types.Skip
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput> | runtime.Types.Skip
  assignedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null | runtime.Types.Skip
}, "id" | "userId_roleId">

export type UserRoleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  userId?: Prisma.SortOrder | runtime.Types.Skip
  roleId?: Prisma.SortOrder | runtime.Types.Skip
  assignedAt?: Prisma.SortOrder | runtime.Types.Skip
  assignedById?: Prisma.SortOrderInput | Prisma.SortOrder | runtime.Types.Skip
  _count?: Prisma.UserRoleCountOrderByAggregateInput | runtime.Types.Skip
  _max?: Prisma.UserRoleMaxOrderByAggregateInput | runtime.Types.Skip
  _min?: Prisma.UserRoleMinOrderByAggregateInput | runtime.Types.Skip
}

export type UserRoleScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserRoleScalarWhereWithAggregatesInput | Prisma.UserRoleScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  OR?: Prisma.UserRoleScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  NOT?: Prisma.UserRoleScalarWhereWithAggregatesInput | Prisma.UserRoleScalarWhereWithAggregatesInput[] | runtime.Types.Skip
  id?: Prisma.StringWithAggregatesFilter<"UserRole"> | string | runtime.Types.Skip
  userId?: Prisma.StringWithAggregatesFilter<"UserRole"> | string | runtime.Types.Skip
  roleId?: Prisma.StringWithAggregatesFilter<"UserRole"> | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeWithAggregatesFilter<"UserRole"> | Date | string | runtime.Types.Skip
  assignedById?: Prisma.StringNullableWithAggregatesFilter<"UserRole"> | string | null | runtime.Types.Skip
}

export type UserRoleCreateInput = {
  id?: string | runtime.Types.Skip
  assignedAt?: Date | string | runtime.Types.Skip
  user: Prisma.UserCreateNestedOneWithoutUserRolesInput
  role: Prisma.RoleCreateNestedOneWithoutUsersInput
  assignedBy?: Prisma.UserCreateNestedOneWithoutAssignedRolesInput | runtime.Types.Skip
}

export type UserRoleUncheckedCreateInput = {
  id?: string | runtime.Types.Skip
  userId: string
  roleId: string
  assignedAt?: Date | string | runtime.Types.Skip
  assignedById?: string | null | runtime.Types.Skip
}

export type UserRoleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  user?: Prisma.UserUpdateOneRequiredWithoutUserRolesNestedInput | runtime.Types.Skip
  role?: Prisma.RoleUpdateOneRequiredWithoutUsersNestedInput | runtime.Types.Skip
  assignedBy?: Prisma.UserUpdateOneWithoutAssignedRolesNestedInput | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  userId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  roleId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null | runtime.Types.Skip
}

export type UserRoleCreateManyInput = {
  id?: string | runtime.Types.Skip
  userId: string
  roleId: string
  assignedAt?: Date | string | runtime.Types.Skip
  assignedById?: string | null | runtime.Types.Skip
}

export type UserRoleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  userId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  roleId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null | runtime.Types.Skip
}

export type UserRoleListRelationFilter = {
  every?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  some?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  none?: Prisma.UserRoleWhereInput | runtime.Types.Skip
}

export type UserRoleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder | runtime.Types.Skip
}

export type UserRoleUserIdRoleIdCompoundUniqueInput = {
  userId: string
  roleId: string
}

export type UserRoleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  userId?: Prisma.SortOrder | runtime.Types.Skip
  roleId?: Prisma.SortOrder | runtime.Types.Skip
  assignedAt?: Prisma.SortOrder | runtime.Types.Skip
  assignedById?: Prisma.SortOrder | runtime.Types.Skip
}

export type UserRoleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  userId?: Prisma.SortOrder | runtime.Types.Skip
  roleId?: Prisma.SortOrder | runtime.Types.Skip
  assignedAt?: Prisma.SortOrder | runtime.Types.Skip
  assignedById?: Prisma.SortOrder | runtime.Types.Skip
}

export type UserRoleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder | runtime.Types.Skip
  userId?: Prisma.SortOrder | runtime.Types.Skip
  roleId?: Prisma.SortOrder | runtime.Types.Skip
  assignedAt?: Prisma.SortOrder | runtime.Types.Skip
  assignedById?: Prisma.SortOrder | runtime.Types.Skip
}

export type UserRoleCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutUserInput, Prisma.UserRoleUncheckedCreateWithoutUserInput> | Prisma.UserRoleCreateWithoutUserInput[] | Prisma.UserRoleUncheckedCreateWithoutUserInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutUserInput | Prisma.UserRoleCreateOrConnectWithoutUserInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyUserInputEnvelope | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
}

export type UserRoleCreateNestedManyWithoutAssignedByInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutAssignedByInput, Prisma.UserRoleUncheckedCreateWithoutAssignedByInput> | Prisma.UserRoleCreateWithoutAssignedByInput[] | Prisma.UserRoleUncheckedCreateWithoutAssignedByInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutAssignedByInput | Prisma.UserRoleCreateOrConnectWithoutAssignedByInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyAssignedByInputEnvelope | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
}

export type UserRoleUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutUserInput, Prisma.UserRoleUncheckedCreateWithoutUserInput> | Prisma.UserRoleCreateWithoutUserInput[] | Prisma.UserRoleUncheckedCreateWithoutUserInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutUserInput | Prisma.UserRoleCreateOrConnectWithoutUserInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyUserInputEnvelope | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
}

export type UserRoleUncheckedCreateNestedManyWithoutAssignedByInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutAssignedByInput, Prisma.UserRoleUncheckedCreateWithoutAssignedByInput> | Prisma.UserRoleCreateWithoutAssignedByInput[] | Prisma.UserRoleUncheckedCreateWithoutAssignedByInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutAssignedByInput | Prisma.UserRoleCreateOrConnectWithoutAssignedByInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyAssignedByInputEnvelope | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
}

export type UserRoleUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutUserInput, Prisma.UserRoleUncheckedCreateWithoutUserInput> | Prisma.UserRoleCreateWithoutUserInput[] | Prisma.UserRoleUncheckedCreateWithoutUserInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutUserInput | Prisma.UserRoleCreateOrConnectWithoutUserInput[] | runtime.Types.Skip
  upsert?: Prisma.UserRoleUpsertWithWhereUniqueWithoutUserInput | Prisma.UserRoleUpsertWithWhereUniqueWithoutUserInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyUserInputEnvelope | runtime.Types.Skip
  set?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  disconnect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  delete?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  update?: Prisma.UserRoleUpdateWithWhereUniqueWithoutUserInput | Prisma.UserRoleUpdateWithWhereUniqueWithoutUserInput[] | runtime.Types.Skip
  updateMany?: Prisma.UserRoleUpdateManyWithWhereWithoutUserInput | Prisma.UserRoleUpdateManyWithWhereWithoutUserInput[] | runtime.Types.Skip
  deleteMany?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
}

export type UserRoleUpdateManyWithoutAssignedByNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutAssignedByInput, Prisma.UserRoleUncheckedCreateWithoutAssignedByInput> | Prisma.UserRoleCreateWithoutAssignedByInput[] | Prisma.UserRoleUncheckedCreateWithoutAssignedByInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutAssignedByInput | Prisma.UserRoleCreateOrConnectWithoutAssignedByInput[] | runtime.Types.Skip
  upsert?: Prisma.UserRoleUpsertWithWhereUniqueWithoutAssignedByInput | Prisma.UserRoleUpsertWithWhereUniqueWithoutAssignedByInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyAssignedByInputEnvelope | runtime.Types.Skip
  set?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  disconnect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  delete?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  update?: Prisma.UserRoleUpdateWithWhereUniqueWithoutAssignedByInput | Prisma.UserRoleUpdateWithWhereUniqueWithoutAssignedByInput[] | runtime.Types.Skip
  updateMany?: Prisma.UserRoleUpdateManyWithWhereWithoutAssignedByInput | Prisma.UserRoleUpdateManyWithWhereWithoutAssignedByInput[] | runtime.Types.Skip
  deleteMany?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutUserInput, Prisma.UserRoleUncheckedCreateWithoutUserInput> | Prisma.UserRoleCreateWithoutUserInput[] | Prisma.UserRoleUncheckedCreateWithoutUserInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutUserInput | Prisma.UserRoleCreateOrConnectWithoutUserInput[] | runtime.Types.Skip
  upsert?: Prisma.UserRoleUpsertWithWhereUniqueWithoutUserInput | Prisma.UserRoleUpsertWithWhereUniqueWithoutUserInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyUserInputEnvelope | runtime.Types.Skip
  set?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  disconnect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  delete?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  update?: Prisma.UserRoleUpdateWithWhereUniqueWithoutUserInput | Prisma.UserRoleUpdateWithWhereUniqueWithoutUserInput[] | runtime.Types.Skip
  updateMany?: Prisma.UserRoleUpdateManyWithWhereWithoutUserInput | Prisma.UserRoleUpdateManyWithWhereWithoutUserInput[] | runtime.Types.Skip
  deleteMany?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateManyWithoutAssignedByNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutAssignedByInput, Prisma.UserRoleUncheckedCreateWithoutAssignedByInput> | Prisma.UserRoleCreateWithoutAssignedByInput[] | Prisma.UserRoleUncheckedCreateWithoutAssignedByInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutAssignedByInput | Prisma.UserRoleCreateOrConnectWithoutAssignedByInput[] | runtime.Types.Skip
  upsert?: Prisma.UserRoleUpsertWithWhereUniqueWithoutAssignedByInput | Prisma.UserRoleUpsertWithWhereUniqueWithoutAssignedByInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyAssignedByInputEnvelope | runtime.Types.Skip
  set?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  disconnect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  delete?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  update?: Prisma.UserRoleUpdateWithWhereUniqueWithoutAssignedByInput | Prisma.UserRoleUpdateWithWhereUniqueWithoutAssignedByInput[] | runtime.Types.Skip
  updateMany?: Prisma.UserRoleUpdateManyWithWhereWithoutAssignedByInput | Prisma.UserRoleUpdateManyWithWhereWithoutAssignedByInput[] | runtime.Types.Skip
  deleteMany?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
}

export type UserRoleCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutRoleInput, Prisma.UserRoleUncheckedCreateWithoutRoleInput> | Prisma.UserRoleCreateWithoutRoleInput[] | Prisma.UserRoleUncheckedCreateWithoutRoleInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutRoleInput | Prisma.UserRoleCreateOrConnectWithoutRoleInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyRoleInputEnvelope | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
}

export type UserRoleUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutRoleInput, Prisma.UserRoleUncheckedCreateWithoutRoleInput> | Prisma.UserRoleCreateWithoutRoleInput[] | Prisma.UserRoleUncheckedCreateWithoutRoleInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutRoleInput | Prisma.UserRoleCreateOrConnectWithoutRoleInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyRoleInputEnvelope | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
}

export type UserRoleUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutRoleInput, Prisma.UserRoleUncheckedCreateWithoutRoleInput> | Prisma.UserRoleCreateWithoutRoleInput[] | Prisma.UserRoleUncheckedCreateWithoutRoleInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutRoleInput | Prisma.UserRoleCreateOrConnectWithoutRoleInput[] | runtime.Types.Skip
  upsert?: Prisma.UserRoleUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserRoleUpsertWithWhereUniqueWithoutRoleInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyRoleInputEnvelope | runtime.Types.Skip
  set?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  disconnect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  delete?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  update?: Prisma.UserRoleUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserRoleUpdateWithWhereUniqueWithoutRoleInput[] | runtime.Types.Skip
  updateMany?: Prisma.UserRoleUpdateManyWithWhereWithoutRoleInput | Prisma.UserRoleUpdateManyWithWhereWithoutRoleInput[] | runtime.Types.Skip
  deleteMany?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.UserRoleCreateWithoutRoleInput, Prisma.UserRoleUncheckedCreateWithoutRoleInput> | Prisma.UserRoleCreateWithoutRoleInput[] | Prisma.UserRoleUncheckedCreateWithoutRoleInput[] | runtime.Types.Skip
  connectOrCreate?: Prisma.UserRoleCreateOrConnectWithoutRoleInput | Prisma.UserRoleCreateOrConnectWithoutRoleInput[] | runtime.Types.Skip
  upsert?: Prisma.UserRoleUpsertWithWhereUniqueWithoutRoleInput | Prisma.UserRoleUpsertWithWhereUniqueWithoutRoleInput[] | runtime.Types.Skip
  createMany?: Prisma.UserRoleCreateManyRoleInputEnvelope | runtime.Types.Skip
  set?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  disconnect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  delete?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  connect?: Prisma.UserRoleWhereUniqueInput | Prisma.UserRoleWhereUniqueInput[] | runtime.Types.Skip
  update?: Prisma.UserRoleUpdateWithWhereUniqueWithoutRoleInput | Prisma.UserRoleUpdateWithWhereUniqueWithoutRoleInput[] | runtime.Types.Skip
  updateMany?: Prisma.UserRoleUpdateManyWithWhereWithoutRoleInput | Prisma.UserRoleUpdateManyWithWhereWithoutRoleInput[] | runtime.Types.Skip
  deleteMany?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
}

export type UserRoleCreateWithoutUserInput = {
  id?: string | runtime.Types.Skip
  assignedAt?: Date | string | runtime.Types.Skip
  role: Prisma.RoleCreateNestedOneWithoutUsersInput
  assignedBy?: Prisma.UserCreateNestedOneWithoutAssignedRolesInput | runtime.Types.Skip
}

export type UserRoleUncheckedCreateWithoutUserInput = {
  id?: string | runtime.Types.Skip
  roleId: string
  assignedAt?: Date | string | runtime.Types.Skip
  assignedById?: string | null | runtime.Types.Skip
}

export type UserRoleCreateOrConnectWithoutUserInput = {
  where: Prisma.UserRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRoleCreateWithoutUserInput, Prisma.UserRoleUncheckedCreateWithoutUserInput>
}

export type UserRoleCreateManyUserInputEnvelope = {
  data: Prisma.UserRoleCreateManyUserInput | Prisma.UserRoleCreateManyUserInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

export type UserRoleCreateWithoutAssignedByInput = {
  id?: string | runtime.Types.Skip
  assignedAt?: Date | string | runtime.Types.Skip
  user: Prisma.UserCreateNestedOneWithoutUserRolesInput
  role: Prisma.RoleCreateNestedOneWithoutUsersInput
}

export type UserRoleUncheckedCreateWithoutAssignedByInput = {
  id?: string | runtime.Types.Skip
  userId: string
  roleId: string
  assignedAt?: Date | string | runtime.Types.Skip
}

export type UserRoleCreateOrConnectWithoutAssignedByInput = {
  where: Prisma.UserRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRoleCreateWithoutAssignedByInput, Prisma.UserRoleUncheckedCreateWithoutAssignedByInput>
}

export type UserRoleCreateManyAssignedByInputEnvelope = {
  data: Prisma.UserRoleCreateManyAssignedByInput | Prisma.UserRoleCreateManyAssignedByInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

export type UserRoleUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserRoleWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRoleUpdateWithoutUserInput, Prisma.UserRoleUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserRoleCreateWithoutUserInput, Prisma.UserRoleUncheckedCreateWithoutUserInput>
}

export type UserRoleUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserRoleWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRoleUpdateWithoutUserInput, Prisma.UserRoleUncheckedUpdateWithoutUserInput>
}

export type UserRoleUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserRoleScalarWhereInput
  data: Prisma.XOR<Prisma.UserRoleUpdateManyMutationInput, Prisma.UserRoleUncheckedUpdateManyWithoutUserInput>
}

export type UserRoleScalarWhereInput = {
  AND?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
  OR?: Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
  NOT?: Prisma.UserRoleScalarWhereInput | Prisma.UserRoleScalarWhereInput[] | runtime.Types.Skip
  id?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  userId?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  roleId?: Prisma.StringFilter<"UserRole"> | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFilter<"UserRole"> | Date | string | runtime.Types.Skip
  assignedById?: Prisma.StringNullableFilter<"UserRole"> | string | null | runtime.Types.Skip
}

export type UserRoleUpsertWithWhereUniqueWithoutAssignedByInput = {
  where: Prisma.UserRoleWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRoleUpdateWithoutAssignedByInput, Prisma.UserRoleUncheckedUpdateWithoutAssignedByInput>
  create: Prisma.XOR<Prisma.UserRoleCreateWithoutAssignedByInput, Prisma.UserRoleUncheckedCreateWithoutAssignedByInput>
}

export type UserRoleUpdateWithWhereUniqueWithoutAssignedByInput = {
  where: Prisma.UserRoleWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRoleUpdateWithoutAssignedByInput, Prisma.UserRoleUncheckedUpdateWithoutAssignedByInput>
}

export type UserRoleUpdateManyWithWhereWithoutAssignedByInput = {
  where: Prisma.UserRoleScalarWhereInput
  data: Prisma.XOR<Prisma.UserRoleUpdateManyMutationInput, Prisma.UserRoleUncheckedUpdateManyWithoutAssignedByInput>
}

export type UserRoleCreateWithoutRoleInput = {
  id?: string | runtime.Types.Skip
  assignedAt?: Date | string | runtime.Types.Skip
  user: Prisma.UserCreateNestedOneWithoutUserRolesInput
  assignedBy?: Prisma.UserCreateNestedOneWithoutAssignedRolesInput | runtime.Types.Skip
}

export type UserRoleUncheckedCreateWithoutRoleInput = {
  id?: string | runtime.Types.Skip
  userId: string
  assignedAt?: Date | string | runtime.Types.Skip
  assignedById?: string | null | runtime.Types.Skip
}

export type UserRoleCreateOrConnectWithoutRoleInput = {
  where: Prisma.UserRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.UserRoleCreateWithoutRoleInput, Prisma.UserRoleUncheckedCreateWithoutRoleInput>
}

export type UserRoleCreateManyRoleInputEnvelope = {
  data: Prisma.UserRoleCreateManyRoleInput | Prisma.UserRoleCreateManyRoleInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

export type UserRoleUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserRoleWhereUniqueInput
  update: Prisma.XOR<Prisma.UserRoleUpdateWithoutRoleInput, Prisma.UserRoleUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.UserRoleCreateWithoutRoleInput, Prisma.UserRoleUncheckedCreateWithoutRoleInput>
}

export type UserRoleUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.UserRoleWhereUniqueInput
  data: Prisma.XOR<Prisma.UserRoleUpdateWithoutRoleInput, Prisma.UserRoleUncheckedUpdateWithoutRoleInput>
}

export type UserRoleUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.UserRoleScalarWhereInput
  data: Prisma.XOR<Prisma.UserRoleUpdateManyMutationInput, Prisma.UserRoleUncheckedUpdateManyWithoutRoleInput>
}

export type UserRoleCreateManyUserInput = {
  id?: string | runtime.Types.Skip
  roleId: string
  assignedAt?: Date | string | runtime.Types.Skip
  assignedById?: string | null | runtime.Types.Skip
}

export type UserRoleCreateManyAssignedByInput = {
  id?: string | runtime.Types.Skip
  userId: string
  roleId: string
  assignedAt?: Date | string | runtime.Types.Skip
}

export type UserRoleUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  role?: Prisma.RoleUpdateOneRequiredWithoutUsersNestedInput | runtime.Types.Skip
  assignedBy?: Prisma.UserUpdateOneWithoutAssignedRolesNestedInput | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  roleId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  roleId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null | runtime.Types.Skip
}

export type UserRoleUpdateWithoutAssignedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  user?: Prisma.UserUpdateOneRequiredWithoutUserRolesNestedInput | runtime.Types.Skip
  role?: Prisma.RoleUpdateOneRequiredWithoutUsersNestedInput | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateWithoutAssignedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  userId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  roleId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateManyWithoutAssignedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  userId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  roleId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
}

export type UserRoleCreateManyRoleInput = {
  id?: string | runtime.Types.Skip
  userId: string
  assignedAt?: Date | string | runtime.Types.Skip
  assignedById?: string | null | runtime.Types.Skip
}

export type UserRoleUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  user?: Prisma.UserUpdateOneRequiredWithoutUserRolesNestedInput | runtime.Types.Skip
  assignedBy?: Prisma.UserUpdateOneWithoutAssignedRolesNestedInput | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  userId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null | runtime.Types.Skip
}

export type UserRoleUncheckedUpdateManyWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  userId?: Prisma.StringFieldUpdateOperationsInput | string | runtime.Types.Skip
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string | runtime.Types.Skip
  assignedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null | runtime.Types.Skip
}



export type UserRoleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean | runtime.Types.Skip
  userId?: boolean | runtime.Types.Skip
  roleId?: boolean | runtime.Types.Skip
  assignedAt?: boolean | runtime.Types.Skip
  assignedById?: boolean | runtime.Types.Skip
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs> | runtime.Types.Skip
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs> | runtime.Types.Skip
  assignedBy?: boolean | Prisma.UserRole$assignedByArgs<ExtArgs> | runtime.Types.Skip
}, ExtArgs["result"]["userRole"]>

export type UserRoleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean | runtime.Types.Skip
  userId?: boolean | runtime.Types.Skip
  roleId?: boolean | runtime.Types.Skip
  assignedAt?: boolean | runtime.Types.Skip
  assignedById?: boolean | runtime.Types.Skip
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs> | runtime.Types.Skip
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs> | runtime.Types.Skip
  assignedBy?: boolean | Prisma.UserRole$assignedByArgs<ExtArgs> | runtime.Types.Skip
}, ExtArgs["result"]["userRole"]>

export type UserRoleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean | runtime.Types.Skip
  userId?: boolean | runtime.Types.Skip
  roleId?: boolean | runtime.Types.Skip
  assignedAt?: boolean | runtime.Types.Skip
  assignedById?: boolean | runtime.Types.Skip
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs> | runtime.Types.Skip
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs> | runtime.Types.Skip
  assignedBy?: boolean | Prisma.UserRole$assignedByArgs<ExtArgs> | runtime.Types.Skip
}, ExtArgs["result"]["userRole"]>

export type UserRoleSelectScalar = {
  id?: boolean | runtime.Types.Skip
  userId?: boolean | runtime.Types.Skip
  roleId?: boolean | runtime.Types.Skip
  assignedAt?: boolean | runtime.Types.Skip
  assignedById?: boolean | runtime.Types.Skip
}

export type UserRoleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "roleId" | "assignedAt" | "assignedById", ExtArgs["result"]["userRole"], runtime.Types.Skip>
export type UserRoleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs> | runtime.Types.Skip
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs> | runtime.Types.Skip
  assignedBy?: boolean | Prisma.UserRole$assignedByArgs<ExtArgs> | runtime.Types.Skip
}
export type UserRoleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs> | runtime.Types.Skip
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs> | runtime.Types.Skip
  assignedBy?: boolean | Prisma.UserRole$assignedByArgs<ExtArgs> | runtime.Types.Skip
}
export type UserRoleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs> | runtime.Types.Skip
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs> | runtime.Types.Skip
  assignedBy?: boolean | Prisma.UserRole$assignedByArgs<ExtArgs> | runtime.Types.Skip
}

export type $UserRolePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserRole"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    role: Prisma.$RolePayload<ExtArgs>
    assignedBy: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    roleId: string
    assignedAt: Date
    assignedById: string | null
  }, ExtArgs["result"]["userRole"]>
  composites: {}
}

export type UserRoleGetPayload<S extends boolean | null | undefined | UserRoleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserRolePayload, S>

export type UserRoleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserRoleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserRoleCountAggregateInputType | true
  }

export interface UserRoleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserRole'], meta: { name: 'UserRole' } }
  /**
   * Find zero or one UserRole that matches the filter.
   * @param {UserRoleFindUniqueArgs} args - Arguments to find a UserRole
   * @example
   * // Get one UserRole
   * const userRole = await prisma.userRole.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserRoleFindUniqueArgs>(args: Prisma.SelectSubset<T, UserRoleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserRole that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserRoleFindUniqueOrThrowArgs} args - Arguments to find a UserRole
   * @example
   * // Get one UserRole
   * const userRole = await prisma.userRole.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserRoleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserRoleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRole that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleFindFirstArgs} args - Arguments to find a UserRole
   * @example
   * // Get one UserRole
   * const userRole = await prisma.userRole.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserRoleFindFirstArgs>(args?: Prisma.SelectSubset<T, UserRoleFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserRole that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleFindFirstOrThrowArgs} args - Arguments to find a UserRole
   * @example
   * // Get one UserRole
   * const userRole = await prisma.userRole.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserRoleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserRoleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserRoles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserRoles
   * const userRoles = await prisma.userRole.findMany()
   * 
   * // Get first 10 UserRoles
   * const userRoles = await prisma.userRole.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userRoleWithIdOnly = await prisma.userRole.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserRoleFindManyArgs>(args?: Prisma.SelectSubset<T, UserRoleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserRole.
   * @param {UserRoleCreateArgs} args - Arguments to create a UserRole.
   * @example
   * // Create one UserRole
   * const UserRole = await prisma.userRole.create({
   *   data: {
   *     // ... data to create a UserRole
   *   }
   * })
   * 
   */
  create<T extends UserRoleCreateArgs>(args: Prisma.SelectSubset<T, UserRoleCreateArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserRoles.
   * @param {UserRoleCreateManyArgs} args - Arguments to create many UserRoles.
   * @example
   * // Create many UserRoles
   * const userRole = await prisma.userRole.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserRoleCreateManyArgs>(args?: Prisma.SelectSubset<T, UserRoleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserRoles and returns the data saved in the database.
   * @param {UserRoleCreateManyAndReturnArgs} args - Arguments to create many UserRoles.
   * @example
   * // Create many UserRoles
   * const userRole = await prisma.userRole.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserRoles and only return the `id`
   * const userRoleWithIdOnly = await prisma.userRole.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserRoleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserRoleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserRole.
   * @param {UserRoleDeleteArgs} args - Arguments to delete one UserRole.
   * @example
   * // Delete one UserRole
   * const UserRole = await prisma.userRole.delete({
   *   where: {
   *     // ... filter to delete one UserRole
   *   }
   * })
   * 
   */
  delete<T extends UserRoleDeleteArgs>(args: Prisma.SelectSubset<T, UserRoleDeleteArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserRole.
   * @param {UserRoleUpdateArgs} args - Arguments to update one UserRole.
   * @example
   * // Update one UserRole
   * const userRole = await prisma.userRole.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserRoleUpdateArgs>(args: Prisma.SelectSubset<T, UserRoleUpdateArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserRoles.
   * @param {UserRoleDeleteManyArgs} args - Arguments to filter UserRoles to delete.
   * @example
   * // Delete a few UserRoles
   * const { count } = await prisma.userRole.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserRoleDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserRoleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserRoles
   * const userRole = await prisma.userRole.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserRoleUpdateManyArgs>(args: Prisma.SelectSubset<T, UserRoleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserRoles and returns the data updated in the database.
   * @param {UserRoleUpdateManyAndReturnArgs} args - Arguments to update many UserRoles.
   * @example
   * // Update many UserRoles
   * const userRole = await prisma.userRole.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserRoles and only return the `id`
   * const userRoleWithIdOnly = await prisma.userRole.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserRoleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserRoleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserRole.
   * @param {UserRoleUpsertArgs} args - Arguments to update or create a UserRole.
   * @example
   * // Update or create a UserRole
   * const userRole = await prisma.userRole.upsert({
   *   create: {
   *     // ... data to create a UserRole
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserRole we want to update
   *   }
   * })
   */
  upsert<T extends UserRoleUpsertArgs>(args: Prisma.SelectSubset<T, UserRoleUpsertArgs<ExtArgs>>): Prisma.Prisma__UserRoleClient<runtime.Types.Result.GetResult<Prisma.$UserRolePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleCountArgs} args - Arguments to filter UserRoles to count.
   * @example
   * // Count the number of UserRoles
   * const count = await prisma.userRole.count({
   *   where: {
   *     // ... the filter for the UserRoles we want to count
   *   }
   * })
  **/
  count<T extends UserRoleCountArgs>(
    args?: Prisma.Subset<T, UserRoleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserRoleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserRoleAggregateArgs>(args: Prisma.Subset<T, UserRoleAggregateArgs>): Prisma.PrismaPromise<GetUserRoleAggregateType<T>>

  /**
   * Group by UserRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserRoleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserRoleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserRoleGroupByArgs['orderBy'] }
      : { orderBy?: UserRoleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserRoleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserRoleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserRole model
 */
readonly fields: UserRoleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserRole.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserRoleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  role<T extends Prisma.RoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleDefaultArgs<ExtArgs>>): Prisma.Prisma__RoleClient<runtime.Types.Result.GetResult<Prisma.$RolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  assignedBy<T extends Prisma.UserRole$assignedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserRole$assignedByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserRole model
 */
export interface UserRoleFieldRefs {
  readonly id: Prisma.FieldRef<"UserRole", 'String'>
  readonly userId: Prisma.FieldRef<"UserRole", 'String'>
  readonly roleId: Prisma.FieldRef<"UserRole", 'String'>
  readonly assignedAt: Prisma.FieldRef<"UserRole", 'DateTime'>
  readonly assignedById: Prisma.FieldRef<"UserRole", 'String'>
}
    

// Custom InputTypes
/**
 * UserRole findUnique
 */
export type UserRoleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * Filter, which UserRole to fetch.
   */
  where: Prisma.UserRoleWhereUniqueInput
}

/**
 * UserRole findUniqueOrThrow
 */
export type UserRoleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * Filter, which UserRole to fetch.
   */
  where: Prisma.UserRoleWhereUniqueInput
}

/**
 * UserRole findFirst
 */
export type UserRoleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * Filter, which UserRole to fetch.
   */
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoles to fetch.
   */
  orderBy?: Prisma.UserRoleOrderByWithRelationInput | Prisma.UserRoleOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRoles.
   */
  cursor?: Prisma.UserRoleWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoles from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoles.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRoles.
   */
  distinct?: Prisma.UserRoleScalarFieldEnum | Prisma.UserRoleScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * UserRole findFirstOrThrow
 */
export type UserRoleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * Filter, which UserRole to fetch.
   */
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoles to fetch.
   */
  orderBy?: Prisma.UserRoleOrderByWithRelationInput | Prisma.UserRoleOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserRoles.
   */
  cursor?: Prisma.UserRoleWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoles from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoles.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRoles.
   */
  distinct?: Prisma.UserRoleScalarFieldEnum | Prisma.UserRoleScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * UserRole findMany
 */
export type UserRoleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * Filter, which UserRoles to fetch.
   */
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserRoles to fetch.
   */
  orderBy?: Prisma.UserRoleOrderByWithRelationInput | Prisma.UserRoleOrderByWithRelationInput[] | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserRoles.
   */
  cursor?: Prisma.UserRoleWhereUniqueInput | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserRoles from the position of the cursor.
   */
  take?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserRoles.
   */
  skip?: number | runtime.Types.Skip
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserRoles.
   */
  distinct?: Prisma.UserRoleScalarFieldEnum | Prisma.UserRoleScalarFieldEnum[] | runtime.Types.Skip
}

/**
 * UserRole create
 */
export type UserRoleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * The data needed to create a UserRole.
   */
  data: Prisma.XOR<Prisma.UserRoleCreateInput, Prisma.UserRoleUncheckedCreateInput>
}

/**
 * UserRole createMany
 */
export type UserRoleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserRoles.
   */
  data: Prisma.UserRoleCreateManyInput | Prisma.UserRoleCreateManyInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
}

/**
 * UserRole createManyAndReturn
 */
export type UserRoleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * The data used to create many UserRoles.
   */
  data: Prisma.UserRoleCreateManyInput | Prisma.UserRoleCreateManyInput[]
  skipDuplicates?: boolean | runtime.Types.Skip
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserRole update
 */
export type UserRoleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * The data needed to update a UserRole.
   */
  data: Prisma.XOR<Prisma.UserRoleUpdateInput, Prisma.UserRoleUncheckedUpdateInput>
  /**
   * Choose, which UserRole to update.
   */
  where: Prisma.UserRoleWhereUniqueInput
}

/**
 * UserRole updateMany
 */
export type UserRoleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserRoles.
   */
  data: Prisma.XOR<Prisma.UserRoleUpdateManyMutationInput, Prisma.UserRoleUncheckedUpdateManyInput>
  /**
   * Filter which UserRoles to update
   */
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  /**
   * Limit how many UserRoles to update.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * UserRole updateManyAndReturn
 */
export type UserRoleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * The data used to update UserRoles.
   */
  data: Prisma.XOR<Prisma.UserRoleUpdateManyMutationInput, Prisma.UserRoleUncheckedUpdateManyInput>
  /**
   * Filter which UserRoles to update
   */
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  /**
   * Limit how many UserRoles to update.
   */
  limit?: number | runtime.Types.Skip
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserRole upsert
 */
export type UserRoleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * The filter to search for the UserRole to update in case it exists.
   */
  where: Prisma.UserRoleWhereUniqueInput
  /**
   * In case the UserRole found by the `where` argument doesn't exist, create a new UserRole with this data.
   */
  create: Prisma.XOR<Prisma.UserRoleCreateInput, Prisma.UserRoleUncheckedCreateInput>
  /**
   * In case the UserRole was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserRoleUpdateInput, Prisma.UserRoleUncheckedUpdateInput>
}

/**
 * UserRole delete
 */
export type UserRoleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
  /**
   * Filter which UserRole to delete.
   */
  where: Prisma.UserRoleWhereUniqueInput
}

/**
 * UserRole deleteMany
 */
export type UserRoleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserRoles to delete
   */
  where?: Prisma.UserRoleWhereInput | runtime.Types.Skip
  /**
   * Limit how many UserRoles to delete.
   */
  limit?: number | runtime.Types.Skip
}

/**
 * UserRole.assignedBy
 */
export type UserRole$assignedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput | runtime.Types.Skip
}

/**
 * UserRole without action
 */
export type UserRoleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRole
   */
  select?: Prisma.UserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRole
   */
  omit?: Prisma.UserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRoleInclude<ExtArgs> | null
}
